spring.application.name=pickleball-backend
#spring.datasource.url=jdbc:mysql://localhost:3306/pickleball
spring.datasource.url=jdbc:mysql://mysql:3306/pickleball
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

spring.main.allow-circular-references=true

jwt.access.secret=Z3dlMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFyc3Q=
jwt.refresh.secret=Z3dlMTIzNDU2Nzg5YWJjZGVmZ2hpamtsbW5vcHFyc3Q=
jwt.access.expiration=60000
jwt.refresh.expiration=120000

#spring.data.redis.host=localhost
spring.data.redis.host=redis
spring.data.redis.port=6379

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

payos.client-id=7226c6bd-e1dd-4d3c-a779-58c9518f83b5
payos.api-key=852697c0-33c5-414e-83a2-17ad952851a0
payos.checksum-key=c28c1561f410aacebf2b20dfee5678bd5941a382108562f5fabe59aeaef65522
payos.return-url=https://your-frontend.com/payment-success
payos.cancel-url=https://your-frontend.com/payment-cancel

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phucp9698@gmail.com
spring.mail.password=lolftkugkckkiwul
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

resend.api-key=re_4tSNJnYe_CVUKZS6f4fQ7buywhFdW2nGg
resend.from-email=noreply@crm.singles

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

#RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest


spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.amqp=DEBUG

# S? thread consumer ch?y song song
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2
