spring.application.name=pickleball-backend

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

# JWT
jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

# PayOS
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.return-url=${PAYOS_RETURN_URL}
payos.cancel-url=${PAYOS_CANCEL_URL}

# Email
resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL}

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

spring.main.allow-circular-references=true

spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.amqp=DEBUG